package packaging

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"text/template"
	"time"
)

type RPMBuildOptions struct {
	Runtime       string
	Name          string
	Version       string
	Release       string
	Arch          string
	Summary       string
	License       string
	URL           string
	InstallPrefix string

	PayloadDir string
	OutDir     string
}

func BuildRPMFromPayload(ctx context.Context, runner CommandRunner, opts RPMBuildOptions) (BuildResult, error) {
	start := time.Now()

	if runner == nil {
		return BuildResult{}, fmt.Errorf("runner is required")
	}
	if opts.Runtime == "" {
		return BuildResult{}, fmt.Errorf("runtime is required")
	}
	if opts.Name == "" || opts.Version == "" || opts.Release == "" {
		return BuildResult{}, fmt.Errorf("name, version, and release are required")
	}
	if opts.PayloadDir == "" {
		return BuildResult{}, fmt.Errorf("payload dir is required")
	}
	if opts.OutDir == "" {
		return BuildResult{}, fmt.Errorf("out dir is required")
	}
	if opts.InstallPrefix == "" {
		return BuildResult{}, fmt.Errorf("install prefix is required")
	}

	topDir, err := os.MkdirTemp("", "cdprun-rpmbuild-*")
	if err != nil {
		return BuildResult{}, fmt.Errorf("create rpmbuild dir: %w", err)
	}
	defer func() { _ = os.RemoveAll(topDir) }()

	for _, d := range []string{"BUILD", "BUILDROOT", "RPMS", "SOURCES", "SPECS", "SRPMS"} {
		if err := os.MkdirAll(filepath.Join(topDir, d), 0755); err != nil {
			return BuildResult{}, fmt.Errorf("create rpmbuild subdir %s: %w", d, err)
		}
	}

	sourceTar := fmt.Sprintf("%s-%s.tar.gz", opts.Name, opts.Version)
	sourceTarPath := filepath.Join(topDir, "SOURCES", sourceTar)

	// Create a source tarball from the payload root.
	if _, _, err := runner.Run(ctx, "", "tar", []string{"-czf", sourceTarPath, "-C", opts.PayloadDir, "."}, nil); err != nil {
		return BuildResult{}, err
	}

	specPath := filepath.Join(topDir, "SPECS", opts.Name+".spec")
	spec, err := renderRPMSpec(rpmSpecParams{
		Name:          opts.Name,
		Version:       opts.Version,
		Release:       opts.Release,
		Summary:       nonEmpty(opts.Summary, fmt.Sprintf("%s runtime", opts.Name)),
		License:       nonEmpty(opts.License, "Proprietary"),
		URL:           nonEmpty(opts.URL, "https://example.invalid"),
		SourceTarball: sourceTar,
		InstallPrefix: opts.InstallPrefix,
	})
	if err != nil {
		return BuildResult{}, fmt.Errorf("render spec: %w", err)
	}
	if err := os.WriteFile(specPath, []byte(spec), 0644); err != nil {
		return BuildResult{}, fmt.Errorf("write spec: %w", err)
	}

	if _, _, err := runner.Run(ctx, "", "rpmbuild", []string{
		"-bb", specPath,
		"--define", fmt.Sprintf("_topdir %s", topDir),
	}, nil); err != nil {
		return BuildResult{}, err
	}

	rpms, err := filepath.Glob(filepath.Join(topDir, "RPMS", "*", "*.rpm"))
	if err != nil {
		return BuildResult{}, fmt.Errorf("glob rpms: %w", err)
	}
	if len(rpms) == 0 {
		return BuildResult{}, fmt.Errorf("no rpm produced under %s", filepath.Join(topDir, "RPMS"))
	}

	// Copy first RPM into out dir (phase 2 is a debug tool; multi-arch/multi-output later).
	if err := os.MkdirAll(opts.OutDir, 0755); err != nil {
		return BuildResult{}, fmt.Errorf("create out dir: %w", err)
	}

	outPath := filepath.Join(opts.OutDir, filepath.Base(rpms[0]))
	if _, _, err := runner.Run(ctx, "", "cp", []string{"-f", rpms[0], outPath}, nil); err != nil {
		return BuildResult{}, err
	}

	outSHA, err := ComputeFileSHA256(outPath)
	if err != nil {
		return BuildResult{}, err
	}

	return BuildResult{
		Runtime:         opts.Runtime,
		PackageType:     PackageTypeRPM,
		PackageName:     opts.Name,
		Version:         opts.Version,
		Release:         opts.Release,
		Arch:            opts.Arch,
		InstallPrefix:   opts.InstallPrefix,
		PackageFilename: filepath.Base(outPath),
		PackagePath:     outPath,
		PackageSHA256:   outSHA,
		Duration:        time.Since(start),
	}, nil
}

func nonEmpty(v string, fallback string) string {
	if v == "" {
		return fallback
	}
	return v
}

type rpmSpecParams struct {
	Name          string
	Version       string
	Release       string
	Summary       string
	License       string
	URL           string
	SourceTarball string
	InstallPrefix string
}

func renderRPMSpec(p rpmSpecParams) (string, error) {
	tpl, err := template.New("spec").Parse(rpmSpecTemplate)
	if err != nil {
		return "", err
	}
	var buf bytes.Buffer
	if err := tpl.Execute(&buf, p); err != nil {
		return "", err
	}
	return buf.String(), nil
}

const rpmSpecTemplate = `# Generated by cdprun (phase 2)

Name:           {{.Name}}
Version:        {{.Version}}
Release:        {{.Release}}%{?dist}
Summary:        {{.Summary}}

License:        {{.License}}
URL:            {{.URL}}
Source0:        {{.SourceTarball}}

AutoReqProv:    no
%global debug_package %{nil}
%define __strip /bin/true
%define _build_id_links none
%undefine __brp_mangle_shebangs
%define __brp_check_rpaths %{nil}
%define __brp_ldconfig %{nil}

%description
{{.Name}} installed under {{.InstallPrefix}}.

%prep
%setup -q -c -T
mkdir -p payload
tar -xzf %{SOURCE0} -C payload

%build
# no build (payload is pre-staged)

%install
mkdir -p %{buildroot}
cp -a payload/. %{buildroot}/

%files
{{.InstallPrefix}}
`
